## **Multiplicação de Matrizes:** Implementação _sequencial_, _Multithreading_ e _Multiprocessos_.

***

Este projeto visa observar as diferenças entre a implementação de algoritmos utilizando as abordagens sequencial, Multithreading e Multiprocessos, realizando testes de implementação e comparativos em termos de desempenho utilizando a linguagem **Python**, para a disciplina **Sistemas Operacionais** do curso de Bacharelado em Tecnologia da Informação, oferecido pela Universidade Federal do Rio Grande do Norte.

**Desenvolvido por:** José Manoel Freitas da Silva

***

### **1. Introdução**

A multiplicação de matrizes é uma operação fundamental em álgebra linear que desempenha um papel crucial em diversos campos da ciência da computação, engenharia e ciências exatas. Uma das principais vantagens da utilização desse método é a sua natureza altamente paralelizável, uma vez que multiplicação de matrizes é bastante suscetível à distribuição de tarefas, seja por meio de threads, em um ambiente multithread, ou por processos. Além disso, a multiplicação de matrizes pode ser escalada para grandes conjuntos de dados e dimensões, o que a torna relevante para problemas de alta complexidade encontrados em pesquisa científica e aplicações industriais.

Desse modo, iremos utilizar de uma de suas propriedades, chamada **independência de dados**, que nos permite calcular cada elemento da matriz resultante de forma independente dos demais dados da matriz, para implementar diversos conceitos da multiprogramação e analisar questões fundamentais de desempenho e otimização algorítmica, ressaltando a sua importância prática e sua capacidade de aproveitar ao máximo os recursos computacionais modernos. 

### **2. Metodologia**

Para esse projeto será feito 3 implementações, sendo elas:

* Uma implementação **Sequencial**, sem a utilização de multiprocessos ou multithreading;
* Uma implementação utilizando **Threads**;
* Uma implementação utilizando **Processos**.

Cada uma das implementações receberá duas matrizes **M1** e **M2** de tamanho **C**x**L** variados, com valores e dimensões randomizadas por meio de um algorítimo auxiliar implementado em **Python**. Para as implementações em multiprocessamento será utilizado ainda uma segunda variável **P**, que determina a quantidade de elementos que serão processados em cada thread ou processo criado, de modo a evitar problemas oriundos do excesso de processos abertos, frequentemente vistos em matrizes consideravelmente grandes.

Para quantificar o desempenho de cada implementação será medido o tempo de execução em cada uma das metodologias, realizando a plotagem de gráficos de desempenho com o intuito de visualizar o **tempo médio geral** e o **tempo médio em função de P**.

### **3. Considerações iniciais**

Nesse projeto, devido ao seu caráter analítico, será utilizado a linguagem de programação **Python**, aliada ao **Jupyter Notebook**, onde iremos observar o comportamento de diferentes formas de implementação de um mesmo algoritmo com o intuito de analisar as vantagens e desvantagens de **aplicações sequenciais** e **paralelas**.

A escolha dessas duas ferramentas se deve ao fato de permitir produzir gráficos e relatórios com facilidade quando utilizadas em conjunto com algumas bibliotecas, como a _multiprocessing_, _threading_,_matplotlib_ e a _numpy_, que terá um papel fundamental na criação de objetos e elementos utilizados durante os testes.

### **4. Multiplicação de matrizes**

#### **4.1. Operações entre matrizes**

Uma matriz pode ser definida como uma estrutura matemática que organiza elementos em **linhas** e **colunas**, formando uma grade bidimensional. Nela cada elemento é identificado por sua posição única na matriz através do índice de linhas e colunas. Por exemplo, na matriz $A$, de dimensões 3x3, o elemento $A[i][j]$ é identificado pela linha $i$ e coluna $j$.

\begin{equation*}

A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9

\end{bmatrix}

\end{equation*}

Assim, o elemento $A_{1,2}$ da matriz $A$ é igual a **2**.

Essa estrutura também está suscetível a algumas operações, como a multiplicação entre matrizes, que será utilizada como objeto de estudo.

A **multiplicação de matrizes** é uma operação que corresponde ao  produto de duas matrizes $A$ e $B$, para produzir uma terceira matriz $C$. Para calcular o elemento $C_{i,j}$ da matriz resultante $C$, devemos multiplicar os elementos da linha $i$ da matriz $A$ pelos elementos da coluna $j$ da matriz $B$, somando os produtos. Matematicamente, isso pode ser expresso como:

\begin{equation*}
C_{i,j} = A_{i,1} \cdot B_{1,j} + A_{i,2} \cdot B_{2,j} + \ldots + A_{i,n} \cdot B_{n,j}
\end{equation*}

Esse processo é repetido para todos os elementos da matriz resultante $C$, e o resultado é uma nova matriz que é o produto das matrizes $A$ e $B$, com a quantidade colunas de $A$ e linhas de $B$, assim como veremos nos algoritmos implementados a seguir.

### **5. Algoritmos e implementações** 

#### **5.1. Importando recursos**

Para a implementação dos algoritmos a seguir utilizaremos as seguintes bibliotecas:

* **numpy:** Biblioteca em Python que fornece suporte para arrays multidimensionais e funções matemáticas de alto desempenho para manipulação de dados numéricos;
* **time:** Biblioteca em Python utilizada para lidar com operações relacionadas ao tempo, como o tempo de execução de algoritmos;

In [176]:
import numpy as np
import time

#### **5.2. Criando matrizes**

Nesse estudo serão utilizadas matrizes de inteiros construídas de forma randômica através da função **_get_random_matrix_**, que utiliza a função **_random_**, da biblioteca **NumPy**. Para fins de estudos todos os elementos irão possuir um valor fixado entre 1 e 10. Além das matrizes randômicas, também iremos utilizar matrizes inicializadas com zeros por meio da função **_initialize_matrix_**, necessária para garantir que todos os elementos da matriz resultante tenham um valor inicial conhecido e consistente.

Vale ressaltar que para ocorrer a multiplicação entre matrizes a quantidade de linhas de $A$ e colunas de $B$ deve possuir o mesmo valor, seguindo a propriedade a seguir:

\begin{equation*}
[A_{m \times n}] \cdot [B_{n \times p}] = [C_{m \times p}]
\end{equation*}

Desse modo, para satisfazer essa condição, iremos utilizar a variável **_cond_** para garantir que ambas as matrizes criadas obedeçam essa propriedade.

In [177]:
def get_random_matrix(rows, cols):
    # Cria matrizes aleatórias com valores 1 e 10
    return np.random.randint(1, 11, size = (rows, cols))

In [178]:
def initialize_matrix(rows, cols):
    return np.zeros((rows, cols))

In [179]:
# Limite para o tamanho das matrizes
limit = 10

In [180]:
# Condição para existencia do produto
cond = np.random.randint(2, limit)

# Cria matrizes de tamanhos aleatórios
matrix1 = get_random_matrix(np.random.randint(2, limit), cond)
matrix2 = get_random_matrix(cond, np.random.randint(2, limit))

# Imprima as matrizes
print("Matriz 1 de tamanho", matrix1.shape)
print(matrix1)
print("\n")
print("Matriz 2 de tamanho", matrix2.shape)
print(matrix2)


Matriz 1 de tamanho (9, 7)
[[ 2  9  3  2  4  4  8]
 [10  7  7  3  4  7  1]
 [ 5  7  8  8  2  7  5]
 [ 3  2 10  2  4  5  5]
 [ 4  6  2  9 10  5  5]
 [ 3  4  7  4  9 10  4]
 [ 9  2  1  9  6  8  9]
 [ 5 10  4  8  5  6  7]
 [10  8  3  9  3  1  1]]


Matriz 2 de tamanho (7, 7)
[[ 5  2  6  8  6  9  7]
 [ 2 10  7  1 10  6  2]
 [ 4  7  2  3  9  6  2]
 [ 3  5  4  1  3  1  3]
 [ 9  1  2  3  5  6  3]
 [ 7  6  9  8  7  2  1]
 [ 9 10  1  2  6  6 10]]


#### **5.3. Matriz resultante**

Com a finalidade de facilitar a visualização de cada resultado em diferentes implementações, será utilizado um objeto **_Resultante_** para armazenar os dados obtidos em cada execução, composto por:

* **matrix:** matriz resultante;
* **process_time:** tempo de execução;
* **P:** quantidade de elementos que serão processados em cada thread ou processo criado.

Onde **_P_** receberá valor **-1** caso seja uma execução sequencial.

In [181]:
class Resultante:
    def __init__(self, matrix, process_time, P = -1):
        self.matrix = matrix
        self.process_time = process_time
        self.P = P

#### **5.4. Implementação Sequencial**

A implementação sequencial a seguir é responsável por multiplicar duas matrizes, **_matrix1_** e **_matrix2_**, de acordo com o algoritmo tradicional de multiplicação utilizando três loops aninhados. O primeiro loop (**_i_**) itera pelas linhas da matriz resultante, o segundo loop (**_j_**) itera pelas colunas da matriz resultante e o terceiro loop (**_k_**) itera pelas colunas da primeira matriz e pelas linhas da segunda matriz. Durante cada iteração, os elementos correspondentes das matrizes de entrada são multiplicados e acumulados no elemento correspondente da matriz resultante.

Após a conclusão da multiplicação, o tempo total de execução é calculado e é retornado um objeto **_Resultante_** que contém a matriz resultante e o tempo total de execução.

In [182]:
def sequential_multiplication(matrix1, matrix2):
    # Inicializa a contagem de tempo
    start = time.time()

    # Inicializa a matriz resultante
    matrix_result = initialize_matrix(matrix1.shape[0], matrix2.shape[1])

    # Realiza a multiplicação de matrizes
    for i in range(matrix1.shape[0]):
        for j in range(matrix2.shape[1]):
            for k in range(matrix1.shape[1]):
                matrix_result[i][j] += matrix1[i][k] * matrix2[k][j]
                
    # Finaliza a contagem de tempo
    end = time.time()

    # Tempo total de execução
    total_time = end - start

    # Cria o objeto resultante
    result = Resultante(matrix_result, total_time)

    return result

In [183]:
result_sequential = sequential_multiplication(matrix1, matrix2)

print(result_sequential.matrix)
print(result_sequential.process_time)
print(result_sequential.P)

[[182. 233. 141.  96. 231. 172. 140.]
 [195. 210. 207. 181. 277. 221. 136.]
 [207. 270. 199. 151. 285. 199. 152.]
 [181. 190. 118. 120. 219. 165. 118.]
 [237. 217. 176. 133. 244. 193. 156.]
 [250. 224. 188. 168. 272. 195. 132.]
 [271. 234. 199. 186. 250. 214. 212.]
 [235. 289. 211. 147. 299. 221. 178.]
 [148. 185. 174. 125. 222. 191. 139.]]
0.018178939819335938
-1
